version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    ports:
      - 80:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm test